"""
    MIDDLEWARE
    - You can add middleware to FastAPI applications.
    - A "middleware" is a function that works with every request before it is processed by any specific path operation. And also with every response before returning it.
    - The middleware function receives:    - To create a middleware you use the decorator @app.middleware("http") on top of a function.

        * The 'request'.
        * A function 'call_next' that will receive the 'request' as a parameter.
            * This function will pass the 'request' to the corresponding path operation.
            * Then it returns the 'response' generated by the corresponding path operation.
        * You can then further modify the 'response' before returning it.
"""

import time 
from fastapi import FastAPI, Request

app = FastAPI()

@app.middleware('http')
async def add_process_time_header(request: Request, call_next):
    print('Request received')
    start_time = time.perf_counter()
    response = await call_next(request)
    process_time = time.perf_counter() - start_time
    response.headers['X-Process-Time'] = str(process_time)
    print('Response generated')
    return response

@app.get('/')
async def home():
    print('Endpoint is running')
    return {'message': 'Hello'}